### PR TITLE
remove catalog add

### PR DESCRIPTION
**Pull request by aharonranyvision**

### CODE REVIEW

**Comment by digger18** [comment]
Why ??????

**Comment by aharonranyvision** [comment]
@digger18 We have also **face-search** mode,  so catalog will be added manually

**Comment by digger18** [comment]
I would create a different 1-liner script for whitelist that passes a parameter to k3s-installer.sh to choose which catalog to add (anyvision or face-search), but in any case I would not cancel the auto-add for the catalog.

**Comment by igaldahan** [comment]
It's leaves us managing 2 installers, it's not something Im happy to do that, it's and options for failure

**Comment by digger18** [comment]
Fixed in https://github.com/AnyVisionltd/k3s-installer/pull/13

**Pull request closed without merging**
